(include-file "include/flavors.lfe")

(defflavor f1 (x y a (m  42) z (share 'f1))
           (f2)
  gettable-instance-variables
  (settable-instance-variables m a z)   ;share is not settable
  inittable-instance-variables)

;; Comment this out to test required-methods.
(defmethod (set-y) (v)
  (set 'y (tuple 'defmethod v)))        ;Same handling autogenerated setters

(defmethod (set-y after) (v)
  (print "f1 after set-y ~p\n" (list self)))

(defmethod (set-a before) (v)
  (print "f1 before set-a ~p\n" (list self)))

(defmethod (one) (x y z)
  (+ x y z))

(defmethod (one before) (w x y z)       ;No such method is defined
  (print "f1 before one ~p\n" (list self)))

(defmethod (one before) (x y z)
  (print "f1 before one ~p\n" (list self)))

(defmethod (one after) (x y z)
  (print "f1 after one ~p\n" (list self))
  self)

(defmethod (two) (x y z)
  (* x y z))

(defmethod (two before) (x y z)
  (print "f1 before two ~p\n" (list self)))

;; A local function called by the methods.
(defun print (f as)
  (lfe_io:format f as))

(endflavor f1)
